- name: Catalogue Setup Server
  hosts: catalogue
  become: yes

  tasks:
    - name: Disable default nodejs repo
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create roboshop system user
      ansible.builtin.user:
        name: roboshop
        comment: "User for running catalogue service"
        system: true
        shell: /sbin/nologin
        home: /app

    - name: Remove old app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create application directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Remove old catalogue zip file
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent

    - name: Download catalogue application code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Unzip catalogue application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install npm dependencies
      community.general.npm:
        path: /app

    - name: Unmask catalogue service
      ansible.builtin.systemd_service:
        name: catalogue
        masked: false

    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB client
      ansible.builtin.package:
        name: mongodb-mongosh
        state: present

    - name: Check catalogue database exists
      ansible.builtin.command: mongosh mongodb.devopsplayground.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
      register: catalogue_output
      changed_when: false

    - name: Print catalogue output
      ansible.builtin.debug:
        msg: "Catalogue DB index is {{ catalogue_output.stdout }}"

    - name: Load products into MongoDB
      ansible.builtin.shell: mongosh --host mongodb.devopsplayground.fun < /app/db/master-data.js
      when: catalogue_output.stdout | int < 0

    - name: Start and enable catalogue service
      ansible.builtin.systemd_service:
        name: catalogue
        enabled: true
        state: restarted
        daemon_reload: true