- name: Catalogue Setup Server  #File name5 : catalogue.yaml
  hosts: catalogue
  become: yes

  tasks:
    - name: disable default nodejs repo
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Create user for catalogue
      ansible.builtin.user:
        name: roboshop
        comment: "User for running catalogue service"
        system: true
        shell: /sbin/nologin
        home: /app

    - name: Create application directory
      ansible.builtin.file:
        state: directory
        path: /app

    - name: Download catalogue application code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Unzip the downloaded file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install npm dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: copy mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB client
      ansible.builtin.package:
        name: mongodb-mongosh
        state: present

    # - name: Connect to mongodb catalogue
    #   ansible.builtin.command: mongosh mongodb.devopsplayground.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    #   register: catalogue_output

    - name: eval catalogue database
      community.mongodb.mongodb_shell:
        eval: "db.getMongo().getDBNames().indexOf('catalogue')"
      register: catalogue_output

    - name: print catalogue output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"