[mongodb]
mongodb-devopsplayground.fun

[redis]
redis-devopsplayground.fun

[mysql]
mysql-devopsplayground.fun

[rabbitmq]
rabbitmq-devopsplayground.fun

[local]
localhost ansible_connection=local

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321