- name: Install MongoDB Server
  hosts: mongodb
  become: yes

  tasks:
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB server
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes


    - name: allow remote connection 
      ansible.builtin.replace:
          path: /etc/mongod.conf
          regexp: 'bindIp: 127.0.0.1'
          replace: 'bindIp: 0.0.0.0'

    - name: Restart MongoDB service
      ansible.builtin.service:
        name: mongod
        state: restarted

