- name: Setup Redis Server
  hosts: redis
  become: yes

  tasks:
    - name: Disable default Redis repo
      ansible.builtin.command: dnf module disable redis -y

    - name: Enable Redis 7
      ansible.builtin.command: dnf module enable redis:7 -y

    - name: Allow remote connection
      ansible.builtin.replace:
        path: /etc/redis/redis.conf   ✅ correct path
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: Disable protected mode
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: "protected-mode"
        line: "protected-mode no"

    - name: Install Redis server
      ansible.builtin.package:
        name: redis
        state: present

    - name: Start and enable Redis service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes