- name: Getting to know more about gather facts
  hosts: Frontend

  tasks:
    - name: Getting to know more about this
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Store OS information
      ansible.builtin.set_fact:
        os_value: "{{ ansible_os_family }}"

    - name: Print stored OS value
      ansible.builtin.debug:
        msg: "OS family is {{ os_value }}"